export const DomainErrors = {
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_ROLE: 'INVALID_ROLE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  CHURCH_NOT_FOUND: 'CHURCH_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
} as const

export type DomainError = (typeof DomainErrors)[keyof typeof DomainErrors]
